### ISSUE TITLE
Doesn't work on Mac 11.2.1

### ISSUE THREAD

**Issue by kesensoy** [luk3thomas/aaws#2]
I like the idea of this script, however I'm unable to move past an error I get when installing 

`aaws:6: = not found`

it seemed to be tied to the return 0, then I set $AWS_PROFILE as an empty value and it moved forward in setting AAWS_AUTOCOMPLETE=default however I'm still getting the same error code

**Comment by luk3thomas** [comment]
Oh hey, I just saw this. What shell are you using?

**Comment by luk3thomas** [comment]
If I switch to `zsh` I see something similar 

```
$ zsh
```

```
$(_aaws_PS1)\e[94m\w\e[90m$(git branch 2> /dev/null | grep -e '\* ' | sed 's/^..\(.*\)/ \1/')\e[39m \n$ aaws
aaws:4: command not found: complete
aaws:6: = not found
```

**Comment by luk3thomas** [comment]
Hi @kesensoy, I recently moved to zsh and finally made a few changes to get the script working. Thanks!
